{{- if .Values.moodle.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.moodle.fullname }}-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.moodle.fullname }}
    app: {{ .Values.moodle.fullname }}
  minReplicas: {{ .Values.moodle.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.moodle.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.moodle.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.moodle.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.moodle.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.moodle.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
---
{{- if .Values.mariadb.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.mariadb.fullname}}-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.mariadb.fullname }}
    app: {{ .Values.mariadb.fullname }}
  minReplicas: {{ .Values.mariadb.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.mariadb.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.mariadb.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.mariadb.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.mariadb.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.mariadb.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
