apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.moodle.volume.name }}
  namespace: {{ .Values.namespace }}
  {{- if and (eq  .Values.volumes.evs.enabled true) (eq .Values.volumes.obs.enabled false)}}
  annotations:
    {{- .Values.volumes.evs.annotations | toYaml | nindent 4}}
  labels:
    {{- .Values.volumes.evs.labels | toYaml | nindent 4}}
spec:
  accessModes:
    - {{ .Values.volumes.evs.spec.accessModes | toYaml }}
  resources:
    requests:
      storage: {{ .Values.moodle.volume.storage }}
  storageClassName: {{ .Values.volumes.evs.spec.storageClassName }}
{{- else if and (eq  .Values.volumes.evs.enabled false) (eq .Values.volumes.obs.enabled true)}}
  annotations:
    {{- .Values.volumes.obs.annotations | toYaml | nindent 4}}
spec:
  accessModes:
    - {{ .Values.volumes.obs.spec.accessModes | toYaml }}
  resources:
    requests:
      storage: {{ .Values.moodle.volume.storage }}
  storageClassName: {{ .Values.volumes.obs.spec.storageClassName }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mariadb.volume.name }}
  namespace: {{ .Values.namespace }}
  {{- if and (eq  .Values.volumes.evs.enabled true) (eq .Values.volumes.obs.enabled false)}}
  annotations:
    {{- .Values.volumes.evs.annotations | toYaml | nindent 4}}
  labels:
    {{- .Values.volumes.evs.labels | toYaml | nindent 4}}
spec:
  accessModes:
    - {{ .Values.volumes.evs.spec.accessModes | toYaml }}
  resources:
    requests:
      storage: {{ .Values.mariadb.volume.storage }}
  storageClassName: {{ .Values.volumes.evs.spec.storageClassName }}
{{- else if and (eq  .Values.volumes.evs.enabled false) (eq .Values.volumes.obs.enabled true)}}
  annotations:
    {{- .Values.volumes.obs.annotations | toYaml | nindent 4}}
spec:
  accessModes:
    - {{ .Values.volumes.obs.spec.accessModes | toYaml }}
  resources:
    requests:
      storage: {{ .Values.mariadb.volume.storage }}
  storageClassName: {{ .Values.volumes.obs.spec.storageClassName }}
{{- end }}
---
