apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.fullname }}
spec:
  ports:
  {{- $ports := .Values.mariadb.service.ports | toYaml }}
    {{- $ports | nindent 4 }}
  selector:
    app: {{ .Values.mariadb.containerlabels.app }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moodle.fullname | replace "-demo" "-elb"}}
  annotations:
    {{- $ann := .Values.moodle.service.annotations | toYaml }}
    {{- $ann | nindent 4 }}
spec:
  type: {{ .Values.moodle.service.spec.type }}
  ports:
    {{- $ports := .Values.moodle.service.spec.ports | toYaml }}
    {{- $ports | nindent 4 }}
  selector:
    app: {{ .Values.moodle.containerlabels.app }}
