apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mariadb.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $key, $val := .Values.mariadb.statefulsetlabels }}
    {{- $key | nindent 4}}: {{ $val }}
    {{- end}}
spec:
  replicas: {{ .Values.mariadb.replicascount }}
  selector:
    matchLabels:
    {{- range $key, $val := .Values.mariadb.containerlabels }}
    {{- $key | nindent 6}}: {{ $val }}
    {{- end}}
  serviceName: "mariadb"
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.mariadb.containerlabels }}
        {{- $key | nindent 8}}: {{ $val }}
        {{- end}}
    spec:
      containers:
      - name: {{ .Values.mariadb.fullname }}
        image: {{.Values.mariadb.image.repository}}:{{.Values.mariadb.image.tag}}
        env:
          {{- $env := .Values.mariadb.spec.env | toYaml}}
          {{- $env := $env | fromYamlArray }}
          {{- range $env := $env }}
          - name: {{ $env.name }}
            value: {{ $env.value | quote}}
          {{- end}}
        ports:
          {{- $ports := .Values.mariadb.spec.ports | toYaml}}
          {{- $ports | nindent 10}}
        volumeMounts:
          - name: {{ .Values.mariadb.volume.name }}
            mountPath: {{ .Values.mariadb.spec.volumeMounts.mountPath }}
      imagePullSecrets:
        - name: key-access
      volumes:
        - name: {{ .Values.mariadb.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.mariadb.volume.name }}
      {{- if eq .Values.mariadb.spec.nodeSelector.enabled true}}
      nodeSelector:
        name: {{ .Values.mariadb.spec.nodeSelector.name}}
      {{- end}}
---
