apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodledata
  namespace: default
  annotations:
    #EVS
    everest.io/disk-volume-type: SAS    # EVS disk type.
    #everest.io/enterprise-project-id: <your_project_id>     # (Optional)
    #SFS
    #volume.beta.kubernetes.io/storage-provisioner: everest-csi-provisioner
    #OBS
    #everest.io/obs-volume-type: STANDARD    # Object storage type.
    #csi.storage.k8s.io/fstype: obsfs        # Instance type.
    #csi.storage.k8s.io/node-publish-secret-name: obs-secret       # Custom secret name.
    #csi.storage.k8s.io/node-publish-secret-namespace: default    # Namespace of the custom secret.
    #everest.io/enterprise-project-id: <your_project_id>     # (Optional) Enterprise project ID. If an enterprise project is specified, use the same enterprise project when creating a PVC. Otherwise, the PVC cannot be bound to a PV.
  labels:
    failure-domain.beta.kubernetes.io/region: "la-north-2"   # Region of the node where the application is to be deployed.
    failure-domain.beta.kubernetes.io/zone: "la-north-2c"       # AZ of the node where the application is to be deployed.
spec:
  accessModes:
    - ReadWriteOnce             # The value must be ReadWriteMany for object storage.
  resources:
    requests:
      storage: 200Gi               # OBS volume capacity.
  storageClassName: csi-disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: default
  annotations:
    #EVS
    everest.io/disk-volume-type: SAS    # EVS disk type.
    #everest.io/enterprise-project-id: <your_project_id>     # (Optional)
    #SFS
    #volume.beta.kubernetes.io/storage-provisioner: everest-csi-provisioner
    #OBS
    #everest.io/obs-volume-type: STANDARD    # Object storage type.
    #csi.storage.k8s.io/fstype: obsfs        # Instance type.
    #csi.storage.k8s.io/node-publish-secret-name: obs-secret       # Custom secret name.
    #csi.storage.k8s.io/node-publish-secret-namespace: default    # Namespace of the custom secret.
    #everest.io/enterprise-project-id: <your_project_id>     # (Optional) Enterprise project ID. If an enterprise project is specified, use the same enterprise project when creating a PVC.>
  labels:
    failure-domain.beta.kubernetes.io/region: "la-north-2"   # Region of the node where the application is to be deployed.
    failure-domain.beta.kubernetes.io/zone: "la-north-2c"       # AZ of the node where the application is to be deployed.
spec:
  accessModes:
    - ReadWriteOnce            # The value must be ReadWriteMany for object storage.
  resources:
    requests:
      storage: 100Gi               # OBS volume capacity.
  storageClassName: csi-disk    # The storage class type is OBS.
