apiVersion: v1
data:
  access.key: <encoded access key> #use echo -n <your access key>|base64 to encode the key
  secret.key: <encoded secret key> #use echo -n <your secret key>|base64 to encode the key
kind: Secret
metadata:
  name: obs-secret
  namespace: default
  labels:
    secret.kubernetes.io/used-by: csi
type: cfe/secure-opaque
