apiVersion: v1
data:
  access.key: Ulg1VkRXVVlKVVdFQ09OMlpFREo=
  secret.key: UVJFYjlNQnRKYklqQksxWmJQN3UzRWxsMVNYQ1M4dnE3cllYNzk2Qg==
kind: Secret
metadata:
  name: obs-secret
  namespace: default
  labels:
    secret.kubernetes.io/used-by: csi
type: cfe/secure-opaque
