apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: moodle-elb
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate:
        '{
            "type": "public",
            "bandwidth_name": "moodle",
            "bandwidth_chargemode":"traffic",
            "bandwidth_size": 300,
            "bandwidth_sharetype": "PER",
            "eip_type": "5_bgp",
            "name": "moodle"
        }'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
    # include support for http/3
    - port: 443
      targetPort: 8443
      protocol: UDP
      name: http3
  selector:
    app: moodle-app
