apiVersion: v1
data:
  access.key: {{ .Values.secret.ak }}
  secret.key: {{ .Values.secret.sk }}
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    secret.kubernetes.io/used-by: csi
type: cfe/secure-opaque
