namespace: default


secret:
  name: key-access
  ak: <encoded_access_key> #use echo -n <your access key>|base64 to encode the key
  sk: <encoded_secret_key> #use echo -n <your secret key>|base64 to encode the key

moodle:
#name of the deployment
  fullname: moodle-demo

#image to be used
  image:
    repository: bitnami/moodle
    pullPolicy: IfNotPresent
    tag: 4.3

#replicas
  replicascount: 1

#deploymentlabels
  deploymentlabels:
    environment: moodle

#Container labels
  containerlabels:
    app: moodle-app
    environment: moodle

#container specs
  spec:
    env:
      - name: MOODLE_DATABASE_HOST
        value: "mariadb"
      - name: MOODLE_DATABASE_PORT_NUMBER
        value: 3306
      - name: MOODLE_DATABASE_USER
        value: "bn_moodle"
      - name: MOODLE_DATABASE_NAME
        value: "bitnami_moodle"
      - name: ALLOW_EMPTY_PASSWORD
        value: "yes"

#resources limits
    resources:
      enabled: true
      limits:
        cpu: 4
        memory: 4Gi
      requests:
        cpu: 1
        memory: 2Gi

#ports
    ports:
      - containerPort: 8080
      - containerPort: 8443

#volume mount information

#node selector for specific node
    nodeSelector:
      enabled: true
      name: moodle

#persistent volume claim
  volume:
#persistent volume claim name
    storage: 200Gi
    dynamic_provision: false
    type: evs
    #only for sfs provisioning
    share_export_location: <your_location>  # Shared path of the SFS volume.
    id: <volume_id>
    reclaim_policy: retain-volume-only

#service to access the moodle pod
  service:
#note: the loadbalancer and publicip will be created dynamically
    annotations:
      kubernetes.io/elb.class: union
      kubernetes.io/elb.autocreate:
        '{
          "type": "public",
          "bandwidth_name": "moodle-demo",
          "bandwidth_chargemode":"traffic",
          "bandwidth_size": 300,
          "bandwidth_sharetype": "PER",
          "eip_type": "5_bgp",
          "name": "moodle-demo"
        }'

#service spec
    spec:
      type: LoadBalancer
      ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
          name: http
        - port: 443
          targetPort: 8443
          protocol: TCP
          name: https
        - port: 443
          targetPort: 8443
          protocol: UDP
          name: http3

#autoscaling
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    #targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 75

mariadb:
#stateful name
  fullname: mariadb
#image to be used

  image:
    repository: bitnami/mariadb
    pullPolicy: IfNotPresent
    tag: "11.2"

#replicas
  replicascount: 1

#statefulset labels
  statefulsetlabels:
    environment: moodle

#container labels
  containerlabels:
    app: mariadb
    environment: moodle

#container specs
  spec:
#environment variables
    env:
      - name: MARIADB_USER
        value: "bn_moodle"
      - name: ALLOW_EMPTY_PASSWORD
        value: "yes"
      - name: MARIADB_DATABASE
        value: "bitnami_moodle"
      - name: MARIADB_CHARACTER_SET
        value: "utf8mb4"
      - name: MARIADB_COLLATE
        value: "utf8mb4_unicode_ci"
#container port
    ports:
      - containerPort: 3306
#resources limits
    resources:
      enabled: false
      limits:
        cpu: 4
        memory: 4Gi
      requests:
        cpu: 1
        memory: 2Gi
    imagePullSecrets:
      - name: obs-secret
#enable for specific node
    nodeSelector:
      enabled: true
      name: moodle

#persistent volume claim
  volume:
    storage: 100Gi
    dynamic_provision: false
    type: evs
    #only for sfs provisioning
    share_export_location: <your_location>  # Shared path of the SFS volume.
    id: <volume_id>
    reclaim_policy: retain-volume-only

#Cluster IP for internal access
  service:
    type: ClusterIP
    ports:
      - port: 3306
        targetPort: 3306
#autoscaling
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    #targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 75

volumes:
#For more information about regions and availability zones see https://developer.huaweicloud.com/intl/en-us/endpoint
#Elastic Volume Services
  pv_reclaim_policy: Delete
  evs:
    region: la-north-2
    zone: la-north-2c
    disk_type: GPSSD

#Scalabel File System
  sfs:

#Object Storage Services
  obs:
    region: la-north-2
